import type { ExternalContextState, LocalEventOpportunity } from '../domain/connectors'

export const demoCalendarText = [
  'BEGIN:VCALENDAR',
  'VERSION:2.0',
  'BEGIN:VEVENT',
  'DTSTART:20260828T190000Z',
  'DTEND:20260828T203000Z',
  'SUMMARY:Private work block',
  'END:VEVENT',
  'BEGIN:VEVENT',
  'DTSTART:20260828T210000Z',
  'DTEND:20260828T220000Z',
  'SUMMARY:Private appointment',
  'END:VEVENT',
  'END:VCALENDAR',
].join('\r\n')

export const demoEventOpportunities: LocalEventOpportunity[] = [
  {
    id: 'event-sketch-circle',
    title: 'Twilight sketch circle',
    whenLabel: 'Tonight at 7:00 PM',
    setting: 'outdoors',
    energy: 'low',
    social: 'optional-contact',
    latitude: 34.0553,
    longitude: -118.2498,
    sourceLabel: 'Privacy-safe demo event catalog',
    freshnessLabel: 'Seeded for Aug 28',
  },
  {
    id: 'event-bookstore-reading',
    title: 'Independent bookstore reading',
    whenLabel: 'Tonight at 7:30 PM',
    setting: 'indoors',
    energy: 'low',
    social: 'optional-contact',
    latitude: 34.0497,
    longitude: -118.2558,
    sourceLabel: 'Privacy-safe demo event catalog',
    freshnessLabel: 'Seeded for Aug 28',
  },
  {
    id: 'event-museum-late-hours',
    title: 'Free museum late hours',
    whenLabel: 'Tonight until 9:00 PM',
    setting: 'indoors',
    energy: 'medium',
    social: 'private',
    latitude: 34.0638,
    longitude: -118.3592,
    sourceLabel: 'Privacy-safe demo event catalog',
    freshnessLabel: 'Seeded for Aug 28',
  },
]

export const initialExternalContextState: ExternalContextState = {
  weather: {
    condition: 'clear',
    label: 'Clear, mild evening',
    temperatureFahrenheit: 72,
    precipitationMillimeters: 0,
    observedAt: '2026-08-28T18:30:00.000Z',
    sourceMode: 'seeded',
    sourceLabel: 'Privacy-safe demo weather',
  },
  calendar: {
    busyBlocks: 0,
    busyMinutes: 0,
    availableMinutes: 30,
    windowStart: '2026-08-28T18:30:00.000Z',
    windowEnd: '2026-08-29T02:30:00.000Z',
    sourceMode: 'disconnected',
    sourceLabel: 'No calendar connected',
  },
  events: demoEventOpportunities,
  connectors: {
    location: {
      id: 'location',
      title: 'Approximate location',
      summary: 'Use the browser location once for weather context. Exact coordinates are discarded after the request.',
      status: 'waiting',
      permission: 'not-requested',
      sourceMode: 'seeded',
      sourceLabel: 'Demo area fallback',
      freshnessLabel: 'No live request made',
      reasonForUse: 'Location can make weather and distance context less generic.',
      dataBoundary: 'No background tracking, history, reverse geocoding, or browser storage.',
    },
    weather: {
      id: 'weather',
      title: 'Weather',
      summary: 'Current conditions can replace the seeded weather filter after a one-time location request.',
      status: 'ready',
      permission: 'demo-only',
      sourceMode: 'seeded',
      sourceLabel: 'Privacy-safe demo weather',
      freshnessLabel: 'Seeded for Aug 28',
      reasonForUse: 'Outdoor ideas should yield to rain, heat, or darkness.',
      dataBoundary: 'Only current conditions are normalized. Exact coordinates are not retained.',
    },
    calendar: {
      id: 'calendar',
      title: 'Calendar availability',
      summary: 'Import an ICS file locally to calculate open time without retaining titles, people, places, or notes.',
      status: 'waiting',
      permission: 'not-requested',
      sourceMode: 'disconnected',
      sourceLabel: 'No calendar connected',
      freshnessLabel: 'Waiting for you',
      reasonForUse: 'Nora should not offer a 20-minute activity inside a five-minute gap.',
      dataBoundary: 'The browser keeps only busy block count, busy minutes, and the largest useful gap.',
    },
    events: {
      id: 'events',
      title: 'Local events',
      summary: 'A privacy-safe catalog demonstrates how nearby opportunities can be ranked without claiming live listings.',
      status: 'ready',
      permission: 'demo-only',
      sourceMode: 'seeded',
      sourceLabel: 'Privacy-safe demo event catalog',
      freshnessLabel: 'Seeded for Aug 28',
      reasonForUse: 'A timely real-world option can make an invitation concrete without making it compulsory.',
      dataBoundary: 'Listings are seeded. Opening a map remains a separate user action.',
    },
    fitness: {
      id: 'fitness',
      title: 'Somnora Fitness',
      summary: 'Future capability adapter for movement and recovery context.',
      status: 'disconnected',
      permission: 'unavailable',
      sourceMode: 'disconnected',
      sourceLabel: 'Adapter not built',
      freshnessLabel: 'No data',
      reasonForUse: 'Future recovery context could reduce activity demand without exposing raw workouts.',
      dataBoundary: 'No fitness account, HealthKit record, or activity history is available here.',
    },
    nutrition: {
      id: 'nutrition',
      title: 'Somnora Nutrition',
      summary: 'Future capability adapter for meal timing and user-chosen nutrition context.',
      status: 'disconnected',
      permission: 'unavailable',
      sourceMode: 'disconnected',
      sourceLabel: 'Adapter not built',
      freshnessLabel: 'No data',
      reasonForUse: 'Future meal context could prevent tone-deaf suggestions while remaining optional.',
      dataBoundary: 'No meal logs, nutrition account, or dietary inference is available here.',
    },
  },
}
