import type { DemoProfile } from '../domain/types'

export const demoProfile: DemoProfile = {
  id: 'demo-jules-30d',
  displayName: 'Jules',
  summary:
    'A privacy-safe creative profile balancing a demanding project with a desire for more curiosity, movement, and unplanned beauty.',
  metadata: {
    isDemo: true,
    asOfDate: '2026-08-27T19:00:00.000Z',
    windowStart: '2026-07-29',
    windowEnd: '2026-08-27',
    disclosure: 'Seeded, privacy-safe profile. No real account data is loaded.',
  },
  context: {
    weather: 'clear',
    availableMinutes: 28,
    socialBandwidth: 'medium',
    mobility: 'standard',
    energy: 'medium',
  },
  conversations: [
    {
      mode: 'eureka',
      label: 'Eureka',
      entries: [
        {
          id: 'eureka-0823-user',
          mode: 'eureka',
          occurredAt: '2026-08-23T18:12:00.000Z',
          speaker: 'user',
          text: 'The answer finally clicked while I took the long way home.',
          tags: ['breakthrough', 'walking', 'novelty'],
        },
        {
          id: 'eureka-0823-nora',
          mode: 'eureka',
          occurredAt: '2026-08-23T18:13:00.000Z',
          speaker: 'nora',
          text: 'There is a pattern here: your ideas loosen when your surroundings change.',
          tags: ['pattern', 'environment'],
        },
      ],
    },
    {
      mode: 'daily',
      label: 'Daily',
      entries: [
        {
          id: 'daily-0827-user',
          mode: 'daily',
          occurredAt: '2026-08-27T16:40:00.000Z',
          speaker: 'user',
          text: 'I have been productive, but the last few days have felt visually flat.',
          tags: ['workload', 'flatness'],
        },
        {
          id: 'daily-0827-nora',
          mode: 'daily',
          occurredAt: '2026-08-27T16:41:00.000Z',
          speaker: 'nora',
          text: 'You do not sound stuck so much as overexposed to the same room.',
          tags: ['environment', 'observation'],
        },
      ],
    },
    {
      mode: 'dream',
      label: 'Dream',
      entries: [
        {
          id: 'dream-0825-user',
          mode: 'dream',
          occurredAt: '2026-08-25T07:18:00.000Z',
          speaker: 'user',
          text: 'I kept finding bright windows in a building I thought was empty.',
          tags: ['windows', 'light', 'discovery'],
        },
        {
          id: 'dream-0825-nora',
          mode: 'dream',
          occurredAt: '2026-08-25T07:19:00.000Z',
          speaker: 'nora',
          text: 'What do bright windows mean to you when you are awake?',
          tags: ['personal-association', 'imagery'],
        },
      ],
    },
  ],
  evidence: [
    {
      id: 'evidence-long-way-home',
      sourceType: 'journal-entry',
      occurredAt: '2026-08-23T18:12:00.000Z',
      excerpt: 'The answer finally clicked while I took the long way home.',
      conversationId: 'eureka-0823-user',
    },
    {
      id: 'evidence-park-colors',
      sourceType: 'activity-check-in',
      occurredAt: '2026-08-16T20:04:00.000Z',
      excerpt: 'A short park walk helped me notice colors again.',
    },
    {
      id: 'evidence-user-confirmed-novelty',
      sourceType: 'user-confirmation',
      occurredAt: '2026-08-10T17:20:00.000Z',
      excerpt: 'Small changes of scene usually help me reset.',
    },
    {
      id: 'evidence-current-flatness',
      sourceType: 'journal-entry',
      occurredAt: '2026-08-27T16:40:00.000Z',
      excerpt: 'The last few days have felt visually flat.',
      conversationId: 'daily-0827-user',
    },
    {
      id: 'evidence-bright-windows',
      sourceType: 'journal-entry',
      occurredAt: '2026-08-25T07:18:00.000Z',
      excerpt: 'I kept finding bright windows in a building I thought was empty.',
      conversationId: 'dream-0825-user',
    },
    {
      id: 'evidence-broke-late-scroll',
      sourceType: 'user-confirmation',
      occurredAt: '2026-08-06T08:10:00.000Z',
      excerpt: 'I have gone two weeks without taking my phone into bed.',
    },
  ],
  memoryNodes: [
    {
      id: 'self-curious-observer',
      label: 'Curious observer',
      detail: 'You notice small visual details when your pace changes.',
      category: 'user-fact',
      confidence: 'confirmed',
      evidenceIds: ['evidence-user-confirmed-novelty'],
      position: { x: 430, y: 240 },
    },
    {
      id: 'pattern-movement-ideas',
      label: 'Movement loosens ideas',
      detail: 'Creative breakthroughs have followed low-pressure walks.',
      category: 'nora-observation',
      confidence: 'observed',
      evidenceIds: ['evidence-long-way-home', 'evidence-park-colors'],
      position: { x: 120, y: 120 },
    },
    {
      id: 'pattern-scene-change',
      label: 'Scene changes reset attention',
      detail: 'Novel surroundings often restore curiosity without requiring a large plan.',
      category: 'user-fact',
      confidence: 'confirmed',
      evidenceIds: ['evidence-user-confirmed-novelty'],
      position: { x: 120, y: 360 },
    },
    {
      id: 'signal-eureka-gap',
      label: 'Four quiet Eureka days',
      detail: 'No Eureka entry has appeared since August 23.',
      category: 'nora-observation',
      confidence: 'observed',
      evidenceIds: ['evidence-long-way-home'],
      position: { x: 720, y: 90 },
    },
    {
      id: 'signal-visual-flatness',
      label: 'Visual flatness',
      detail: 'The current workload feels productive but visually repetitive.',
      category: 'nora-observation',
      confidence: 'observed',
      evidenceIds: ['evidence-current-flatness'],
      position: { x: 730, y: 300 },
    },
    {
      id: 'interpretation-novelty',
      label: 'Ready for gentle novelty',
      detail: 'A small new environment may fit better than pushing harder in place.',
      category: 'tentative-interpretation',
      confidence: 'tentative',
      evidenceIds: [
        'evidence-current-flatness',
        'evidence-user-confirmed-novelty',
      ],
      position: { x: 980, y: 210 },
    },
    {
      id: 'growth-bedtime-boundary',
      label: 'Broke the late-scroll habit',
      detail: 'A self-directed bedtime boundary has held for two weeks.',
      category: 'growth-marker',
      confidence: 'confirmed',
      evidenceIds: ['evidence-broke-late-scroll'],
      position: { x: 430, y: 500 },
    },
    {
      id: 'imagery-bright-windows',
      label: 'Bright windows',
      detail: 'Recurring imagery that the user associates with possibility.',
      category: 'tentative-interpretation',
      confidence: 'tentative',
      evidenceIds: ['evidence-bright-windows'],
      position: { x: 910, y: 500 },
    },
    {
      id: 'self-image-first',
      label: 'Thinks in images first',
      detail: 'Visual language often arrives before a verbal explanation.',
      category: 'user-fact',
      confidence: 'confirmed',
      evidenceIds: ['evidence-bright-windows'],
      position: { x: 1240, y: 500 },
    },
    {
      id: 'pattern-long-blocks',
      label: 'Long blocks narrow attention',
      detail: 'Extended work in one place can make the day feel visually repetitive.',
      category: 'nora-observation',
      confidence: 'observed',
      evidenceIds: ['evidence-current-flatness'],
      position: { x: 700, y: 650 },
    },
    {
      id: 'growth-self-boundaries',
      label: 'Can hold a boundary',
      detail: 'The bedtime change became a repeated choice, not a one-night experiment.',
      category: 'growth-marker',
      confidence: 'confirmed',
      evidenceIds: ['evidence-broke-late-scroll'],
      position: { x: 150, y: 650 },
    },
    {
      id: 'self-gentle-entry',
      label: 'Responds to gentle entry points',
      detail: 'Small experiments feel more usable than large plans when attention is tight.',
      category: 'user-fact',
      confidence: 'confirmed',
      evidenceIds: ['evidence-user-confirmed-novelty'],
      position: { x: -170, y: 420 },
    },
    {
      id: 'pattern-beauty-attention',
      label: 'Beauty interrupts pressure',
      detail: 'Noticing color and light has coincided with a softer internal pace.',
      category: 'nora-observation',
      confidence: 'observed',
      evidenceIds: ['evidence-park-colors', 'evidence-bright-windows'],
      position: { x: 1250, y: 240 },
    },
    {
      id: 'interpretation-pressure-not-failure',
      label: 'Pressure is not failure',
      detail: 'The current quiet period may reflect repetition and load, not lost creativity.',
      category: 'tentative-interpretation',
      confidence: 'tentative',
      evidenceIds: ['evidence-current-flatness'],
      position: { x: 1040, y: -40 },
    },
    {
      id: 'growth-curiosity-returned',
      label: 'Curiosity has returned before',
      detail: 'The August 23 breakthrough is recent evidence that the capacity is still present.',
      category: 'growth-marker',
      confidence: 'observed',
      evidenceIds: ['evidence-long-way-home'],
      position: { x: 460, y: -70 },
    },
    {
      id: 'interpretation-new-place',
      label: 'A new place may be enough',
      detail: 'A modest shift in environment may fit the present capacity better than a demanding challenge.',
      category: 'tentative-interpretation',
      confidence: 'tentative',
      evidenceIds: ['evidence-user-confirmed-novelty', 'evidence-current-flatness'],
      position: { x: 1260, y: 30 },
    },
    {
      id: 'self-private-processing',
      label: 'Processes privately first',
      detail: 'Reflection works best when sharing stays optional.',
      category: 'user-fact',
      confidence: 'confirmed',
      evidenceIds: ['evidence-user-confirmed-novelty'],
      position: { x: -180, y: 110 },
    },
    {
      id: 'pattern-question-before-meaning',
      label: 'Questions before conclusions',
      detail: 'Personal associations are more useful than fixed interpretations.',
      category: 'nora-observation',
      confidence: 'observed',
      evidenceIds: ['evidence-bright-windows'],
      position: { x: 1130, y: 700 },
    },
  ],
  memoryEdges: [
    {
      id: 'edge-walk-observer',
      source: 'pattern-movement-ideas',
      target: 'self-curious-observer',
      label: 'supports',
      evidenceIds: ['evidence-park-colors'],
    },
    {
      id: 'edge-scene-observer',
      source: 'pattern-scene-change',
      target: 'self-curious-observer',
      label: 'reinforces',
      evidenceIds: ['evidence-user-confirmed-novelty'],
    },
    {
      id: 'edge-gap-novelty',
      source: 'signal-eureka-gap',
      target: 'interpretation-novelty',
      label: 'current signal',
      evidenceIds: ['evidence-long-way-home'],
    },
    {
      id: 'edge-flat-novelty',
      source: 'signal-visual-flatness',
      target: 'interpretation-novelty',
      label: 'current signal',
      evidenceIds: ['evidence-current-flatness'],
    },
    {
      id: 'edge-observer-novelty',
      source: 'self-curious-observer',
      target: 'interpretation-novelty',
      label: 'personal context',
      evidenceIds: ['evidence-user-confirmed-novelty'],
    },
    {
      id: 'edge-growth-scene',
      source: 'growth-bedtime-boundary',
      target: 'pattern-scene-change',
      label: 'shows agency',
      evidenceIds: ['evidence-broke-late-scroll'],
    },
    {
      id: 'edge-image-windows',
      source: 'imagery-bright-windows',
      target: 'self-image-first',
      label: 'expresses',
      evidenceIds: ['evidence-bright-windows'],
    },
    {
      id: 'edge-flat-long-blocks',
      source: 'pattern-long-blocks',
      target: 'signal-visual-flatness',
      label: 'may contribute',
      evidenceIds: ['evidence-current-flatness'],
    },
    {
      id: 'edge-boundary-growth',
      source: 'growth-self-boundaries',
      target: 'growth-bedtime-boundary',
      label: 'demonstrated by',
      evidenceIds: ['evidence-broke-late-scroll'],
    },
    {
      id: 'edge-gentle-scene',
      source: 'self-gentle-entry',
      target: 'pattern-scene-change',
      label: 'shapes',
      evidenceIds: ['evidence-user-confirmed-novelty'],
    },
    {
      id: 'edge-beauty-observer',
      source: 'self-curious-observer',
      target: 'pattern-beauty-attention',
      label: 'expresses',
      evidenceIds: ['evidence-park-colors'],
    },
    {
      id: 'edge-beauty-image',
      source: 'pattern-beauty-attention',
      target: 'self-image-first',
      label: 'supports',
      evidenceIds: ['evidence-bright-windows'],
    },
    {
      id: 'edge-pressure-flat',
      source: 'signal-visual-flatness',
      target: 'interpretation-pressure-not-failure',
      label: 'allows',
      evidenceIds: ['evidence-current-flatness'],
    },
    {
      id: 'edge-return-gap',
      source: 'growth-curiosity-returned',
      target: 'signal-eureka-gap',
      label: 'adds perspective',
      evidenceIds: ['evidence-long-way-home'],
    },
    {
      id: 'edge-new-place-novelty',
      source: 'interpretation-novelty',
      target: 'interpretation-new-place',
      label: 'suggests',
      evidenceIds: ['evidence-user-confirmed-novelty'],
    },
    {
      id: 'edge-private-gentle',
      source: 'self-private-processing',
      target: 'self-gentle-entry',
      label: 'reinforces',
      evidenceIds: ['evidence-user-confirmed-novelty'],
    },
    {
      id: 'edge-question-image',
      source: 'self-image-first',
      target: 'pattern-question-before-meaning',
      label: 'grounds',
      evidenceIds: ['evidence-bright-windows'],
    },
    {
      id: 'edge-question-windows',
      source: 'imagery-bright-windows',
      target: 'pattern-question-before-meaning',
      label: 'keeps tentative',
      evidenceIds: ['evidence-bright-windows'],
    },
  ],
  metrics: [
    { date: '2026-08-21', sleepHours: 7.1, restfulPercent: 76, restingHeartRate: 58, hrvMilliseconds: 47, energy: 'medium' },
    { date: '2026-08-22', sleepHours: 6.6, restfulPercent: 70, restingHeartRate: 60, hrvMilliseconds: 43, energy: 'medium' },
    { date: '2026-08-23', sleepHours: 7.8, restfulPercent: 82, restingHeartRate: 56, hrvMilliseconds: 52, energy: 'high' },
    { date: '2026-08-24', sleepHours: 6.9, restfulPercent: 73, restingHeartRate: 59, hrvMilliseconds: 45, energy: 'medium' },
    { date: '2026-08-25', sleepHours: 6.2, restfulPercent: 66, restingHeartRate: 62, hrvMilliseconds: 39, energy: 'low' },
    { date: '2026-08-26', sleepHours: 7.3, restfulPercent: 78, restingHeartRate: 58, hrvMilliseconds: 48, energy: 'medium' },
    { date: '2026-08-27', sleepHours: 7.0, restfulPercent: 75, restingHeartRate: 59, hrvMilliseconds: 46, energy: 'medium' },
  ],
  themes: [
    { id: 'theme-curiosity', kind: 'emotion', label: 'Curiosity', count: 9, trend: 'rising', note: 'More visible after walks and location changes.', evidenceIds: ['evidence-long-way-home', 'evidence-park-colors'] },
    { id: 'theme-pressure', kind: 'concern', label: 'Creative pressure', count: 7, trend: 'steady', note: 'Usually appears around long uninterrupted work blocks.', evidenceIds: ['evidence-current-flatness'] },
    { id: 'theme-windows', kind: 'imagery', label: 'Windows and light', count: 4, trend: 'rising', note: 'A tentative pattern. Meaning stays personal, not universal.', evidenceIds: ['evidence-bright-windows'] },
    { id: 'theme-self-trust', kind: 'subject', label: 'Self-trust', count: 6, trend: 'rising', note: 'Supported by boundaries that lasted beyond the first week.', evidenceIds: ['evidence-broke-late-scroll'] },
    { id: 'theme-friend-maya', kind: 'person', label: 'Maya', count: 3, trend: 'steady', note: 'Appears in entries about candid feedback and new places.', evidenceIds: ['evidence-user-confirmed-novelty'] },
  ],
  fieldNoteImages: [
    '/assets/demo-field-notes/glass.jpg',
    '/assets/demo-field-notes/ocean.jpg',
    '/assets/demo-field-notes/rain.jpg',
  ],
}

export function getLastConversationEntry(
  profile: DemoProfile,
  mode: 'dream' | 'daily' | 'eureka',
) {
  const thread = profile.conversations.find((item) => item.mode === mode)
  return thread?.entries.at(-1)
}
